import {StyleSheet} from 'react-native';
import {DARK_PURPLE, GOLD, GRADIENT_LIGHT, LIGHT_GREEN, ORCHID} from '../../../constants/colors.ts';
import {ms, vs, isTablet} from '../../../utils/responsive.ts';

export default StyleSheet.create({
    cardWrapper: {
        width: '48%',
        marginBottom: ms(20),
    },
    card: {
        borderRadius: ms(24),
        overflow: 'hidden',
        elevation: 16,
        shadowColor: GRADIENT_LIGHT,
        shadowOffset: {width: 0, height: 8},
        shadowOpacity: 0.5,
        shadowRadius: 16,
        borderWidth: 1.5,
        borderColor: 'rgba(142,45,226,0.3)',
    },
    selectedBorder: {
        position: 'absolute',
        top: -3,
        left: -3,
        right: -3,
        bottom: -3,
        borderRadius: ms(27),
        borderWidth: 3,
        // Constant colour; the pulse is an animated opacity on this view so it
        // can run on the native driver.
        borderColor: 'rgba(142,45,226,1)',
        zIndex: 0,
    },
    preview: {
        width: '100%',
        height: vs(isTablet ? 185 : 148),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,0,0,0.30)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.08)',
        overflow: 'hidden',
    },
    previewSheen: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: '42%',
    },
    // Diagonal glossy highlight that sweeps across the whole card.
    shine: {
        position: 'absolute',
        top: -ms(20),
        bottom: -ms(20),
        width: ms(46),
    },
    info: {
        paddingHorizontal: ms(12),
        paddingTop: ms(12),
        paddingBottom: ms(14),
        alignItems: 'center',
        gap: ms(9),
    },
    title: {
        color: 'white',
        fontSize: ms(13.5),
        fontWeight: '800',
        textAlign: 'center',
        letterSpacing: 0.5,
        textShadowColor: 'rgba(0,0,0,0.35)',
        textShadowOffset: {width: 0, height: 1},
        textShadowRadius: 3,
    },
    priceBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: ms(5),
        paddingHorizontal: ms(14),
        paddingVertical: ms(6),
        borderRadius: ms(20),
        overflow: 'hidden',
    },
    // Absolute-fill gradient background: a flow-positioned LinearGradient jumps to
    // the card's top-left origin on iOS Fabric, so the pill is a plain View and
    // the gradient just paints it.
    priceBadgeBg: {
        ...StyleSheet.absoluteFillObject,
    },
    priceText: {
        fontWeight: '800',
        fontSize: ms(14),
        color: GOLD,
    },
    ownedBadge: {
        paddingHorizontal: ms(14),
        paddingVertical: ms(6),
        borderRadius: ms(20),
        backgroundColor: 'rgba(255,215,0,0.14)',
        borderWidth: 1,
        borderColor: 'rgba(255,215,0,0.32)',
    },
    ownedText: {
        color: GOLD,
        fontWeight: '800',
        fontSize: ms(12),
        letterSpacing: 0.3,
    },
    equippedBadge: {
        paddingHorizontal: ms(14),
        paddingVertical: ms(6),
        borderRadius: ms(20),
        backgroundColor: 'rgba(50,205,50,0.18)',
        borderWidth: 1,
        borderColor: 'rgba(127,255,127,0.3)',
    },
    equippedText: {
        color: LIGHT_GREEN,
        fontWeight: '800',
        fontSize: ms(12),
        letterSpacing: 0.3,
    },
    lockOverlay: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: ms(24),
        alignItems: 'center',
        justifyContent: 'center',
        gap: ms(10),
        zIndex: 5,
    },
    // Small lock tucked into the top-left corner.
    lockCorner: {
        position: 'absolute',
        top: ms(10),
        left: ms(10),
        width: ms(26),
        height: ms(26),
        borderRadius: ms(13),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.12)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.22)',
    },
    // Big centred price pill — the hero of the locked state.
    lockPricePill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: ms(7),
        paddingHorizontal: ms(18),
        paddingVertical: ms(10),
        borderRadius: ms(24),
        backgroundColor: 'rgba(255,215,0,0.16)',
        borderWidth: 1.5,
        borderColor: 'rgba(255,215,0,0.42)',
        elevation: 6,
        shadowColor: GOLD,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.6,
        shadowRadius: 10,
    },
    lockPrice: {
        color: GOLD,
        fontSize: ms(24),
        fontWeight: '900',
        letterSpacing: 0.5,
        textAlign: 'center',
    },
    lockHint: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: ms(11),
        fontWeight: '700',
        letterSpacing: 0.3,
        textAlign: 'center',
    },
    randomBadge: {
        position: 'absolute',
        top: ms(9),
        left: ms(9),
        width: ms(30),
        height: ms(30),
        borderRadius: ms(15),
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 8,
        borderWidth: 1.5,
        borderColor: DARK_PURPLE,
        elevation: 8,
        shadowColor: '#FF49C7',
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.9,
        shadowRadius: 7,
    },
    randomBadgeGradientWrap: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: ms(15),
        overflow: 'hidden',
    },
    randomBadgeGradient: {
        width: '100%',
        height: '100%',
    },
    randomBadgeText: {
        fontSize: ms(13),
        textShadowColor: 'rgba(0,0,0,0.4)',
        textShadowOffset: {width: 0, height: 1},
        textShadowRadius: 2,
    },
    // ── Coming-soon teaser ────────────────────────────────────────────────────
    // A frosted overlay over the whole card so the artwork shows through faintly
    // while clearly reading as "not available yet".
    comingSoonOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(10,0,25,0.55)',
        borderRadius: ms(24),
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 6,
    },
    comingSoonLock: {
        fontSize: ms(26),
        marginBottom: ms(8),
        opacity: 0.95,
    },
    comingSoonPill: {
        paddingHorizontal: ms(12),
        paddingVertical: ms(6),
        borderRadius: ms(20),
        backgroundColor: 'rgba(255,215,0,0.16)',
        borderWidth: 1,
        borderColor: 'rgba(255,215,0,0.45)',
    },
    comingSoonPillText: {
        color: GOLD,
        fontWeight: '900',
        fontSize: ms(11),
        letterSpacing: 1,
        textAlign: 'center',
    },
    // Corner ribbon across the top-right of the card.
    comingSoonRibbon: {
        position: 'absolute',
        top: ms(12),
        right: -ms(28),
        width: ms(110),
        height: ms(22),
        transform: [{rotate: '45deg'}],
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        zIndex: 9,
    },
    comingSoonRibbonBg: {
        ...StyleSheet.absoluteFillObject,
    },
    comingSoonRibbonText: {
        color: '#1a0533',
        fontWeight: '900',
        fontSize: ms(9),
        letterSpacing: 0.8,
    },
    // Bottom badge replacing the price for coming-soon items.
    comingSoonBadge: {
        paddingHorizontal: ms(14),
        paddingVertical: ms(6),
        borderRadius: ms(20),
        backgroundColor: 'rgba(255,255,255,0.10)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.22)',
    },
    comingSoonBadgeText: {
        color: 'rgba(255,255,255,0.85)',
        fontWeight: '800',
        fontSize: ms(12),
        letterSpacing: 0.3,
    },
    squareGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        width: ms(80),
        gap: ms(5),
    },
    squareItem: {
        width: ms(34),
        height: ms(34),
        borderRadius: ms(6),
    },
});
