import {StyleSheet} from 'react-native';
import {GOLD, GRADIENT_LIGHT, LIGHT_GREEN, ORCHID} from '../../../constants/colors.ts';
import {ms, vs, isTablet} from '../../../utils/responsive.ts';

export default StyleSheet.create({
    cardWrapper: {
        width: '48%',
        marginBottom: ms(20),
    },
    card: {
        borderRadius: ms(22),
        overflow: 'hidden',
        elevation: 16,
        shadowColor: GRADIENT_LIGHT,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.5,
        shadowRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(142,45,226,0.3)',
    },
    selectedBorder: {
        position: 'absolute',
        top: -3,
        left: -3,
        right: -3,
        bottom: -3,
        borderRadius: ms(25),
        borderWidth: 3,
        zIndex: 0,
    },
    preview: {
        width: '100%',
        height: vs(isTablet ? 185 : 148),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,0,0,0.32)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.07)',
    },
    info: {
        paddingHorizontal: ms(12),
        paddingVertical: ms(14),
        alignItems: 'center',
        gap: ms(8),
    },
    title: {
        color: 'white',
        fontSize: ms(13),
        fontWeight: '800',
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    priceBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: ms(5),
        paddingHorizontal: ms(14),
        paddingVertical: ms(6),
        borderRadius: ms(20),
    },
    priceText: {
        fontWeight: '800',
        fontSize: ms(14),
        color: GOLD,
    },
    ownedBadge: {
        paddingHorizontal: ms(14),
        paddingVertical: ms(6),
        borderRadius: ms(20),
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.15)',
    },
    ownedText: {
        color: 'rgba(255,255,255,0.65)',
        fontWeight: '700',
        fontSize: ms(12),
        letterSpacing: 0.3,
    },
    equippedBadge: {
        paddingHorizontal: ms(14),
        paddingVertical: ms(6),
        borderRadius: ms(20),
        backgroundColor: 'rgba(50,205,50,0.18)',
        borderWidth: 1,
        borderColor: 'rgba(127,255,127,0.3)',
    },
    equippedText: {
        color: LIGHT_GREEN,
        fontWeight: '800',
        fontSize: ms(12),
        letterSpacing: 0.3,
    },
    lockOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.65)',
        borderRadius: ms(22),
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 5,
    },
    lockText: {
        fontSize: ms(32),
        marginBottom: ms(6),
    },
    lockPrice: {
        color: 'rgba(255,255,255,0.65)',
        fontSize: ms(11),
        fontWeight: '700',
        letterSpacing: 0.3,
    },
    squareGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        width: ms(80),
        gap: ms(5),
    },
    squareItem: {
        width: ms(34),
        height: ms(34),
        borderRadius: ms(6),
    },
});
