import {StyleSheet} from 'react-native';
import {
    BLUISH_PURPLE,
    DARK_PURPLE,
    GOLD,
    ORANGE,
    PLUM,
    PURPLE,
    PURPLE_LIGHT,
    WHITE,
    WHITE_100,
} from '../../../constants/colors.ts';
import {ms, vs, isTablet, SW} from '../../../utils/responsive.ts';

export default StyleSheet.create({
    modalBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: 10,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: isTablet ? Math.min(SW * 0.55, 480) : ms(320),
        padding: ms(25),
        backgroundColor: BLUISH_PURPLE,
        borderRadius: ms(25),
        alignItems: 'center',
        shadowColor: PURPLE_LIGHT,
        shadowOffset: {width: 0, height: 15},
        shadowOpacity: 0.9,
        shadowRadius: 25,
        elevation: 20,
    },
    confettiPlaceholder: {
        position: 'absolute',
        top: ms(10),
        width: '100%',
        alignItems: 'center',
    },
    levelHeader: {
        width: '100%',
        paddingVertical: vs(20),
        borderRadius: ms(20),
        alignItems: 'center',
        marginBottom: vs(20),
        shadowColor: PURPLE_LIGHT,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.9,
        shadowRadius: 20,
        marginTop: vs(50),
    },
    levelText: {
        fontSize: ms(32),
        fontWeight: 'bold',
        color: WHITE,
        textShadowColor: ORANGE,
        textShadowOffset: {width: 0, height: 0},
        textShadowRadius: 15,
        textTransform: 'uppercase',
    },
    messageText: {
        fontSize: ms(16),
        color: WHITE,
        marginBottom: vs(25),
        textAlign: 'center',
    },
    continueButton: {
        width: '48%',
        borderRadius: ms(20),
        overflow: 'hidden',
    },
    buttonGradient: {
        paddingVertical: vs(14),
        borderRadius: ms(20),
        alignItems: 'center',
    },
    buttonText: {
        color: WHITE,
        fontSize: ms(18),
        fontWeight: 'bold',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    loseOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: 10,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loseModal: {
        paddingVertical: vs(30),
        paddingHorizontal: ms(20),
        borderRadius: ms(22),
        backgroundColor: DARK_PURPLE,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: PLUM,
    },
    loseModalActions: {
        maxWidth: '90%',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: ms(15),
        flexWrap: 'wrap',
    },
    loseModalBackAction: {
        paddingVertical: vs(12),
        paddingHorizontal: ms(40),
        borderRadius: ms(15),
        borderWidth: 1,
        borderColor: PURPLE,
    },
    loseTitle: {
        fontSize: ms(28),
        fontWeight: 'bold',
        marginBottom: vs(10),
        textAlign: 'center',
    },
    loseText: {
        color: WHITE_100,
        marginBottom: vs(25),
        fontSize: ms(16),
        textAlign: 'center',
    },
    loseRetry: {
        paddingVertical: vs(14),
        paddingHorizontal: ms(40),
        borderRadius: ms(14),
        alignItems: 'center',
    },
    loseBtnText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: ms(16),
        textAlign: 'center',
    },
    levelContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        top: 0,
        left: '50%',
        transform: [{translateX: -50}],
        paddingHorizontal: ms(12),
        paddingVertical: vs(6),
        borderRadius: 999,
        shadowOpacity: 0.8,
        shadowRadius: 10,
        elevation: 8,
        zIndex: 1,
    },
    levelIcon: {
        fontSize: ms(16),
        marginRight: ms(6),
    },
    levelLabel: {
        color: WHITE,
        fontSize: ms(10),
        marginRight: ms(6),
        fontWeight: '600',
        letterSpacing: 1,
    },
    level: {
        color: WHITE,
        fontSize: ms(16),
        fontWeight: 'bold',
    },
    progressBarFill: {
        backgroundColor: GOLD,
    },
    progressBarEmpty: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    progressBarBackground: {
        position: 'absolute',
        width: '60%',
        flexDirection: 'row',
        height: ms(10),
        borderRadius: ms(5),
        overflow: 'hidden',
        marginBottom: vs(8),
        zIndex: 1,
        top: vs(100),
        left: '17%',
    },
});
