import {StyleSheet} from "react-native";
import {BLACK, GOLD, ORCHID, PURPLE_LIGHT, WHITE} from "../../../constants/colors.ts";

export default StyleSheet.create({
    progressItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 18,
        paddingHorizontal: 18,
        borderRadius: 24,
        marginBottom: 16,
        shadowColor: PURPLE_LIGHT,
        shadowOffset: {width: 0, height: 6},
        shadowOpacity: 0.45,
        shadowRadius: 12,
        elevation: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.15)',
    },
    rankBadge: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.25)',
    },
    rankText: {
        fontSize: 14,
        fontWeight: '800',
        color: WHITE,
    },
    avatar: {
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 2.5,
        borderColor: ORCHID,
        marginRight: 14,
        shadowColor: ORCHID,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.8,
        shadowRadius: 10,
    },
    info: {
        flex: 1,
    },
    levelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    level: {
        fontSize: 18,
        color: WHITE,
        fontWeight: '800',
        letterSpacing: 0.3,
    },
    progressWrapper: {
        marginBottom: 8,
    },
    progressBarBackground: {
        flexDirection: 'row',
        height: 8,
        borderRadius: 4,
        overflow: 'hidden',
        backgroundColor: 'rgba(255,255,255,0.12)',
    },
    progressBarFill: {
        backgroundColor: GOLD,
        borderRadius: 4,
        shadowColor: GOLD,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.9,
        shadowRadius: 6,
    },
    progressBarEmpty: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
    },
    progressLabel: {
        fontSize: 11,
        color: 'rgba(255,255,255,0.5)',
        marginTop: 4,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    scoreRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    score: {
        fontSize: 16,
        color: GOLD,
        fontWeight: '700',
    },
    scoreSuffix: {
        fontSize: 12,
        color: 'rgba(255,255,255,0.5)',
        fontWeight: '600',
    },
});
