import {StyleSheet} from 'react-native';
import {ms, vs} from '../../../utils/responsive.ts';
import {GOLD, PLUM, PURPLE_LIGHT, WHITE} from '../../../constants/colors.ts';

export default StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: ms(24),
        paddingBottom: vs(40),
    },
    illustrationWrap: {
        width: ms(180),
        height: ms(180),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: vs(26),
    },
    halo: {
        position: 'absolute',
        width: ms(180),
        height: ms(180),
        borderRadius: ms(90),
        overflow: 'hidden',
    },
    haloGradient: {
        width: '100%',
        height: '100%',
        borderRadius: ms(90),
    },
    iconCard: {
        width: ms(112),
        height: ms(112),
        borderRadius: ms(32),
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.18)',
        backgroundColor: 'rgba(26,26,46,0.55)',
        shadowColor: PURPLE_LIGHT,
        shadowOffset: {width: 0, height: 10},
        shadowOpacity: 0.45,
        shadowRadius: 20,
        elevation: 12,
    },
    iconCardGradient: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sparkleTopLeft: {
        position: 'absolute',
        top: ms(8),
        left: ms(18),
        fontSize: ms(16),
        color: GOLD,
        textShadowColor: GOLD,
        textShadowRadius: 8,
    },
    sparkleTopRight: {
        position: 'absolute',
        top: ms(20),
        right: ms(10),
        fontSize: ms(12),
        color: PLUM,
        textShadowColor: PLUM,
        textShadowRadius: 6,
    },
    sparkleBottomLeft: {
        position: 'absolute',
        bottom: ms(22),
        left: ms(8),
        fontSize: ms(13),
        color: PLUM,
        textShadowColor: PLUM,
        textShadowRadius: 6,
    },
    title: {
        color: WHITE,
        fontSize: ms(20),
        fontWeight: '800',
        letterSpacing: 0.3,
        textAlign: 'center',
        marginBottom: vs(8),
    },
    subtitle: {
        color: 'rgba(255,255,255,0.65)',
        fontSize: ms(14),
        lineHeight: ms(20),
        textAlign: 'center',
        fontWeight: '500',
        maxWidth: ms(300),
        marginBottom: vs(26),
    },
    ctaWrap: {
        borderRadius: ms(28),
        shadowColor: PURPLE_LIGHT,
        shadowOffset: {width: 0, height: 10},
        shadowOpacity: 0.55,
        shadowRadius: 18,
        elevation: 12,
    },
    ctaButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: vs(54),
        paddingLeft: ms(14),
        paddingRight: ms(26),
        // Pill shape (radius ≈ height / 2) matches the progression CTA.
        borderRadius: ms(28),
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.28)',
        gap: ms(11),
        minWidth: ms(200),
        // Clip the absolute-fill gradient below to the pill's rounded corners.
        overflow: 'hidden',
    },
    ctaGradientFill: {
        ...StyleSheet.absoluteFillObject,
    },
    ctaIcon: {
        width: ms(30),
        height: ms(30),
        borderRadius: ms(15),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.20)',
    },
    ctaIconText: {
        color: WHITE,
        fontSize: ms(16),
        fontWeight: '700',
        marginTop: -1,
    },
    ctaText: {
        color: WHITE,
        fontSize: ms(16),
        fontWeight: '800',
        letterSpacing: 0.6,
    },
});
