import Sound from 'react-native-sound';
import {storage} from '../db/kvStore.ts';
import {STORAGE_KEYS} from './storageKeys.ts';

// ── Sound effects ───────────────────────────────────────────────────────────
// One place that owns every SFX in the game. Background music is separate and
// lives in helpers.ts — that's a single long-running looping track, this is a
// pool of short one-shots, and the two have nothing in common but the library.
//
// Why a module and not `new Sound(...)` at the call site (which is what Play
// used to do):
//
//  • Overlap. A `Sound` instance is one voice: calling play() on one that's
//    already playing restarts it. In a tap game the taps come faster than the
//    120ms sound lasts, so a single instance machine-guns instead of ringing.
//    Sounds listed in VOICES get several instances and round-robin between
//    them, so taps layer the way they do in an arcade cabinet.
//
//  • Speed leaks. setSpeed() mutates the instance, not the call. Play shared
//    ONE instance between the hazard bomb (1x) and the bomb helper (0.25x) and
//    never restored it, so whichever fired last silently repitched the other.
//    playSfx() sets rate on every call — state can't leak between callers.
//
//  • The mute flag. `STORAGE_KEYS.SOUND` is an inverted sentinel (present =
//    muted). Reading it per call would make every tap async; it's cached here
//    and refreshed by the settings toggles.

export type SfxName =
    | 'tap'
    | 'coin'
    | 'heart'
    | 'bomb'
    | 'shield'
    | 'slow'
    | 'hit'
    | 'countdown'
    | 'go'
    // Menu sounds — shop and challenges, not gameplay.
    | 'claim'
    | 'purchase'
    | 'equip'
    | 'denied';

// Generated by scripts/gen-sfx.mjs into android res/raw + the iOS bundle.
const FILES: Record<SfxName, string> = {
    tap: 'tap.wav',
    coin: 'coin.wav',
    heart: 'heart.wav',
    bomb: 'bomb.wav',
    shield: 'shield.wav',
    slow: 'slow.wav',
    hit: 'hit.wav',
    countdown: 'countdown.wav',
    go: 'go.wav',
    claim: 'claim.wav',
    purchase: 'purchase.wav',
    equip: 'equip.wav',
    denied: 'denied.wav',
};

// Extra voices for the sounds that can retrigger before they finish. The rest
// get one — a helper activation or a GO! can't overlap itself.
const VOICES: Partial<Record<SfxName, number>> = {
    tap: 4,
    coin: 2,
    hit: 3,
    // Trying skins on is a fast back-and-forth, so equip retriggers well before
    // its 200ms is up. Two voices are enough — the sound is short by design.
    equip: 2,
};

// Per-sound trim, applied on top of the files' shared loudness target. The
// generator normalises everything to the same peak, which is right for making
// them consistent but not for how often each is heard: tap fires hundreds of
// times a round and needs to sit under the music, bomb is a punctuation mark.
const GAIN: Partial<Record<SfxName, number>> = {
    tap: 0.55,
    hit: 0.6,
    coin: 0.8,
    heart: 0.8,
    countdown: 0.9,
    // Menu sounds play against a quieter mix than gameplay does, so they need
    // less headroom. equip/denied fire on ordinary browsing taps and are trimmed
    // hardest; claim is the one moment worth letting through at full weight.
    equip: 0.45,
    denied: 0.5,
    purchase: 0.85,
    claim: 0.9,
};

interface Pool {
    voices: Sound[];
    next: number;
}

const pools = new Map<SfxName, Pool>();
let muted = false;
let loaded = false;

/** Reads the persisted mute sentinel. Call before the first playSfx(). */
export async function refreshSfxMuted(): Promise<void> {
    muted = !!(await storage.getItem(STORAGE_KEYS.SOUND));
}

/** Lets the settings toggles update the gate without a storage round-trip. */
export function setSfxMuted(value: boolean): void {
    muted = value;
}

export function isSfxMuted(): boolean {
    return muted;
}

/**
 * Loads every effect. Idempotent, so screens can call it on focus without
 * guarding. Loads are async in native; a sound that isn't ready yet simply
 * doesn't play rather than throwing.
 */
export function loadSfx(): void {
    if (loaded) return;
    loaded = true;

    (Object.keys(FILES) as SfxName[]).forEach(name => {
        const count = VOICES[name] ?? 1;
        const voices: Sound[] = [];
        for (let i = 0; i < count; i++) {
            const s: Sound = new Sound(FILES[name], Sound.MAIN_BUNDLE, error => {
                if (error) console.log(`sfx load failed: ${FILES[name]}`, error);
                else s.setVolume(GAIN[name] ?? 1);
            });
            voices.push(s);
        }
        pools.set(name, {voices, next: 0});
    });
}

export function releaseSfx(): void {
    pools.forEach(pool => pool.voices.forEach(v => v.release()));
    pools.clear();
    loaded = false;
}

interface PlayOptions {
    /** Playback rate; also shifts pitch. 1 = as authored. */
    rate?: number;
    /** Multiplies the sound's configured gain, for one call only. */
    volume?: number;
}

export function playSfx(name: SfxName, options: PlayOptions = {}): void {
    if (muted) return;
    const pool = pools.get(name);
    if (!pool) return;

    const voice = pool.voices[pool.next];
    pool.next = (pool.next + 1) % pool.voices.length;
    if (!voice.isLoaded()) return;

    // Both are set every call, never left to whatever the last caller wanted —
    // these instances are shared across the whole app.
    voice.setSpeed(options.rate ?? 1);
    voice.setVolume((GAIN[name] ?? 1) * (options.volume ?? 1));
    voice.setCurrentTime(0);
    voice.play();
}

/** Small random detune, so a repeated sound doesn't machine-gun one pitch. */
export function playSfxVaried(name: SfxName, spread = 0.12, options: PlayOptions = {}): void {
    const rate = 1 + (Math.random() * 2 - 1) * spread;
    playSfx(name, {...options, rate});
}
